module Navbar.View exposing (..)

import Html exposing (..)
import Html.Attributes exposing (..)
import Html.Events exposing (onClick, onInput, onSubmit)
import Navbar.Messages exposing (..)
import Navbar.Model exposing (..)
import RemoteData


view { model, user } =
    nav [ class "navbar navbar-default navbar-static-top m-b-0" ]
        [ div [ class "navbar-header" ]
            [ a [ class "navbar-toggle hidden-sm hidden-md hidden-lg ", href "javascript:void(0)" ]
                [ i [ class "ti-menu" ]
                    []
                ]
            , div [ class "top-left-part" ]
                [ a [ class "logo", href "index.html" ]
                    [ b []
                        [ img [ src "../plugins/images/eliteadmin-logo.png", alt "home" ]
                            []
                        ]
                    , span [ class "hidden-xs" ]
                        [ img [ src "../plugins/images/eliteadmin-text.png", alt "home" ]
                            []
                        ]
                    ]
                ]
            , ul [ class "nav navbar-top-links navbar-left hidden-xs" ]
                [ li []
                    [ a [ href "javascript:void(0)", class "open-close hidden-xs waves-effect waves-light" ]
                        [ i [ class "icon-arrow-left-circle ti-menu" ]
                            []
                        ]
                    ]
                , li []
                    [ Html.form [ class "app-search hidden-xs", onSubmit OnSearch ]
                        [ input [ type_ "text", placeholder "Search...", class "form-control", onInput UpdateSearchText ]
                            []
                        , a [ onClick OnSearch ]
                            [ i [ class "fa fa-search" ]
                                []
                            ]
                        ]
                    ]
                ]
            , ul [ class "nav navbar-top-links navbar-right pull-right" ]
                [ li [ class ("dropdown " ++ model.notificationPanelClasses) ]
                    [ a [ class "dropdown-toggle waves-effect waves-light", href "#", onClick ToggleNotificationPanel ]
                        [ i [ class "icon-envelope" ]
                            []
                        , div [ class "notify" ]
                            [ span [ class "heartbit" ]
                                []
                            , span [ class "point" ]
                                []
                            ]
                        ]
                    , ul [ class "dropdown-menu mailbox scale-up" ]
                        [ li []
                            [ div [ class "drop-title" ]
                                [ text "You have 4 new messages" ]
                            ]
                        , li []
                            [ div [ class "message-center" ]
                                [ a [ href "#" ]
                                    [ div [ class "user-img" ]
                                        [ img [ src "../plugins/images/users/pawandeep.jpg", alt "user", class "img-circle" ]
                                            []
                                        , span [ class "profile-status online pull-right" ]
                                            []
                                        ]
                                    , div [ class "mail-contnet" ]
                                        [ h5 []
                                            [ text "Pavan kumar" ]
                                        , span [ class "mail-desc" ]
                                            [ text "Just see the my admin!" ]
                                        , span [ class "time" ]
                                            [ text "9:30 AM" ]
                                        ]
                                    ]
                                ]
                            ]
                        , li []
                            [ a [ class "text-center", href "javascript:void(0);" ]
                                [ strong []
                                    [ text "See all notifications" ]
                                , i [ class "fa fa-angle-right" ]
                                    []
                                ]
                            ]
                        ]
                    ]
                , li [ class ("dropdown " ++ model.taskPanelClasses) ]
                    [ a [ class "dropdown-toggle waves-effect waves-light", href "#", onClick ToggleTaskPanel ]
                        [ i [ class "icon-note" ]
                            []
                        , div [ class "notify" ]
                            [ span [ class "heartbit" ]
                                []
                            , span [ class "point" ]
                                []
                            ]
                        ]
                    , ul [ class "dropdown-menu dropdown-tasks scale-up" ]
                        [ li []
                            [ a [ href "javascript:void(0)" ]
                                [ div []
                                    [ p []
                                        [ strong []
                                            [ text "Task 1" ]
                                        , span [ class "pull-right text-muted" ]
                                            [ text "40% Complete" ]
                                        ]
                                    , div [ class "progress progress-striped active" ]
                                        [ div [ class "progress-bar progress-bar-success", style [ ( "width", "40%" ) ] ]
                                            [ span [ class "sr-only" ]
                                                [ text "40% Complete (success)" ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        , li [ class "divider" ]
                            []
                        , li []
                            [ a [ class "text-center", href "#" ]
                                [ strong []
                                    [ text "See All Tasks" ]
                                , i [ class "fa fa-angle-right" ]
                                    []
                                ]
                            ]
                        ]
                    ]
                , li [ class ("dropdown " ++ model.userPanelClasses) ]
                    [ (mayBeUser user)
                    , ul [ class "dropdown-menu dropdown-user scale-up" ]
                        [ li []
                            [ a [ href "#" ]
                                [ i [ class "ti-user" ]
                                    []
                                , text "My Profile"
                                ]
                            ]
                        , li []
                            [ a [ href "#" ]
                                [ i [ class "ti-wallet" ]
                                    []
                                , text "My Balance"
                                ]
                            ]
                        , li []
                            [ a [ href "#" ]
                                [ i [ class "ti-email" ]
                                    []
                                , text "Inbox"
                                ]
                            ]
                        , li [ class "divider" ]
                            []
                        , li []
                            [ a [ href "#" ]
                                [ i [ class "ti-settings" ]
                                    []
                                , text "Account Setting"
                                ]
                            ]
                        , li [ class "divider" ]
                            []
                        , li []
                            [ a [ href "#" ]
                                [ i [ class "fa fa-power-off" ]
                                    []
                                , text "Logout"
                                ]
                            ]
                        ]
                    ]
                , li [ class "right-side-toggle" ]
                    [ a [ class "waves-effect waves-light", href "javascript:void(0)" ]
                        [ i [ class "ti-settings" ]
                            []
                        ]
                    ]
                ]
            ]
        ]


spinner =
    div [ class "sk-wave sk-inline" ]
        [ div [ class "sk-rect sk-rect1" ]
            []
        , div [ class "sk-rect sk-rect2" ]
            []
        , div [ class "sk-rect sk-rect3" ]
            []
        , div [ class "sk-rect sk-rect4" ]
            []
        , div [ class "sk-rect sk-rect5" ]
            []
        ]


renderUser user =
    a [ class "dropdown-toggle profile-pic", href "#", onClick ToggleUserPanel ]
        [ img [ src "../plugins/images/users/varun.jpg", alt "user-img", width 36, class "img-circle" ]
            []
        , b [ class "hidden-xs" ]
            [ text user.name ]
        ]


mayBeUser response =
    case response of
        RemoteData.NotAsked ->
            spinner

        RemoteData.Loading ->
            spinner

        RemoteData.Success user ->
            renderUser user

        RemoteData.Failure e ->
            spinner
